### ISSUE TITLE
Form validation in Components

### ISSUE THREAD

**Issue by Morzilla** [why520crazy/ngx-validator#20]
Hi! I'd like to know if it's possible to validate the inputs in an external component inside a main form, like this case:

`<form name="formname" novalidate [ngxFormValidator]="validatorConfig">`
`<section-sec1></section-sec1>`
`<section-sec2></section-sec2>`
`<button type="button" (ngxFormSubmit)="submit()" class="btn btn-primary">Submit</button>`
`</form>`

where inside the `section-sec1` and `section-sec2` I have some input tag like this:

`<input type="text" class="form-control" name="Address" id="Address" [(ngModel)]="Address" required  />`

Thanks!

**Comment by why520crazy** [comment]
Hi, i'm sorry for i miss this issue.

The solution is that inject `NgForm` in `section-sec1` and call ngForm's addControl manually, i add your case (inner-control)  in the demo.

```
@Component({
    selector: 'app-inner-control',
    templateUrl: './inner-control.component.html'
})
export class AppInnerControlComponent implements OnInit {
 
    address: string;

    @ViewChild('addressControl', { static: true }) addressControl: NgModel;

    constructor(private ngForm: NgForm) {}

    ngOnInit(): void {
        this.ngForm.addControl(this.addressControl);
    }
}
```
