### ISSUE TITLE
Unrecognized [ngxFormValidator]

### ISSUE THREAD

**Issue by senzacionale** [why520crazy/ngx-validator#9]
Nice validator, but I have problem with validation

Unrecognized [ngxFormValidator]

`<form [formGroup]="signinForm" (ngxFormSubmit)="signin()" novalidate [ngxFormValidator]="validatorConfig">`

Error:

> core.js:12584 ERROR Error: Uncaught (in promise): Error: Template parse errors:
> Can't bind to 'ngxFormValidator' since it isn't a known property of 'form'. ("ext-18">Sign In</h1>
>           <form [formGroup]="signinForm" (ngxFormSubmit)="signin()" novalidate [ERROR ->][ngxFormValidator]="validatorConfig">
>             <div class="form-group">
>               <label for=""): ng:///SessionsModule/SigninComponent.html@8:79
> Error: Template parse errors:
> Can't bind to 'ngxFormValidator' since it isn't a known property of 'form'. ("ext-18">Sign In</h1>
>           <form [formGroup]="signinForm" (ngxFormSubmit)="signin()" novalidate [ERROR ->][ngxFormValidator]="validatorConfig">
>             <div class="form-group">
>               <label for=""): ng:///SessionsModule/SigninComponent.html@8:79
>     at syntaxError (compiler.js:2547)
>     at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:19495)
>     at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:25041)
>     at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:25028)
>     at compiler.js:24971
>     at Set.forEach (<anonymous>)
>     at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:24971)
>     at compiler.js:24881
>     at Object.then (compiler.js:2538)
>     at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:24880)
>     at resolvePromise (zone.js:814)
>     at resolvePromise (zone.js:771)
>     at zone.js:873
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:14134)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
>     at drainMicroTaskQueue (zone.js:595)

**Comment by senzacionale** [comment]
My mistake. Didn't add

```
NgxValidatorModule.forRoot({
      validationFeedbackStrategy: ValidationFeedbackStrategyBuilder.bootstrap(),
      validateOn: 'submit'
    }),
```

into the right place

**Comment by why520crazy** [comment]
Just saw this issue, welcome to use.
